// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  header_small: dynamic(() => import("./HeaderSmall")),
  hero: dynamic(() => import("./Hero")),
  hero_start: dynamic(() => import("./HeroStart")),
  image_grid4: dynamic(() => import("./ImageGrid4")),
  rich_text: dynamic(() => import("./RichText")),
};
